config-version: 2

name: "jaffle_shop"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

dbt-cloud:
  project-id: 275557 # Put your project id here

profile: default # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["logs"]


target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"
  "environmentname": "SnowflakeDBT"

seeds:
  jaffle_shop:
    +schema: DBT_PKOZIKOWSKI
    jaffle-data:
      +enabled: "{{ var('load_source_data', false) }}"

models:
  finance:
    +database: PC_DBT_DB
    marts/finance:
      +schema: PROD
      +materialized: table
  jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: table
    dagtest:
      groups:
          name: dagtest
          owner:
              email: pawel.kozikowski@gmail.com
    fun:
      schemawar:
          enabled: false 
tests:
  +store_failures: true
  +database: PROD
  +schema: TESTS

